vezetéknév = input('Szia, mi a vezeték neved? ')
Keresztnév = input('És mi a kereszt neved? ')
Születes = input('Mikor születél? ')
csilag = input('Mi a csillagjegyed? ')
print('A te neved ', vezetéknév, ' ', Keresztnév, '.', sep='')
print('Valamint te ', Születes, ' születél és a csillagjegyed pedig ez ', csilag, '.', sep='')
